# Generated by Django 5.2.3 on 2025-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('admin', 'Admin'), ('publisher', 'Publisher')], default='reader', max_length=20),
        ),
    ]
