# Generated by Django 5.2.3 on 2025-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.FileField(blank=True, null=True, upload_to='biography'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='author'),
        ),
    ]
